export interface NameOfAllah {
  id: string;
  arabic: string;
  transliteration: string;
  meaning: string;
  reflection: string;
}

export const namesOfAllah: NameOfAllah[] = [
  {
    id: "ar-rahman",
    arabic: "ٱلرَّحْمَٰنُ",
    transliteration: "Ar-Rahman",
    meaning: "The Most Compassionate",
    reflection: "Reflect on Allah's vast mercy that reaches all creation.",
  },
  {
    id: "ar-rahim",
    arabic: "ٱلرَّحِيمُ",
    transliteration: "Ar-Rahim",
    meaning: "The Most Merciful",
    reflection: "Remember Allah's special mercy for those who turn to Him.",
  },
  {
    id: "al-malik",
    arabic: "ٱلْمَلِكُ",
    transliteration: "Al-Malik",
    meaning: "The King",
    reflection: "Submit to the One who owns all dominion.",
  },
  {
    id: "al-quddus",
    arabic: "ٱلْقُدُّوسُ",
    transliteration: "Al-Quddus",
    meaning: "The Most Pure",
    reflection: "Seek purity in heart and deed through His holiness.",
  },
  {
    id: "as-salam",
    arabic: "ٱلسَّلَامُ",
    transliteration: "As-Salam",
    meaning: "The Source of Peace",
    reflection: "Ask Allah to place peace within your heart and home.",
  },
  {
    id: "al-mumin",
    arabic: "ٱلْمُؤْمِنُ",
    transliteration: "Al-Mu'min",
    meaning: "The Giver of Faith",
    reflection: "Trust that Allah grants safety and faith to the sincere.",
  },
  {
    id: "al-muhaymin",
    arabic: "ٱلْمُهَيْمِنُ",
    transliteration: "Al-Muhaymin",
    meaning: "The Guardian",
    reflection: "Remember Allah's watchful care over every moment.",
  },
  {
    id: "al-aziz",
    arabic: "ٱلْعَزِيزُ",
    transliteration: "Al-Aziz",
    meaning: "The Mighty",
    reflection: "Take strength in Allah's invincible power.",
  },
  {
    id: "al-jabbar",
    arabic: "ٱلْجَبَّارُ",
    transliteration: "Al-Jabbar",
    meaning: "The Compeller",
    reflection: "Let Allah mend what is broken within you.",
  },
  {
    id: "al-mutakabbir",
    arabic: "ٱلْمُتَكَبِّرُ",
    transliteration: "Al-Mutakabbir",
    meaning: "The Supreme",
    reflection: "Honor Allah's greatness and remain humble.",
  },
  {
    id: "al-khaliq",
    arabic: "ٱلْخَالِقُ",
    transliteration: "Al-Khaliq",
    meaning: "The Creator",
    reflection: "See Allah's creativity in every detail around you.",
  },
  {
    id: "al-bari",
    arabic: "ٱلْبَارِئُ",
    transliteration: "Al-Bari'",
    meaning: "The Originator",
    reflection: "Acknowledge Allah's perfect creation from nothing.",
  },
  {
    id: "al-musawwir",
    arabic: "ٱلْمُصَوِّرُ",
    transliteration: "Al-Musawwir",
    meaning: "The Fashioner",
    reflection: "Reflect on the beauty Allah forms in every soul.",
  },
  {
    id: "al-ghaffar",
    arabic: "ٱلْغَفَّارُ",
    transliteration: "Al-Ghaffar",
    meaning: "The Constant Forgiver",
    reflection: "Turn to Allah often; His forgiveness is vast.",
  },
  {
    id: "al-qahhar",
    arabic: "ٱلْقَهَّارُ",
    transliteration: "Al-Qahhar",
    meaning: "The Subduer",
    reflection: "Remember that all power is subdued before Allah.",
  },
  {
    id: "al-wahhab",
    arabic: "ٱلْوَهَّابُ",
    transliteration: "Al-Wahhab",
    meaning: "The Bestower",
    reflection: "Notice the gifts Allah gives without measure.",
  },
  {
    id: "ar-razzaq",
    arabic: "ٱلرَّزَّاقُ",
    transliteration: "Ar-Razzaq",
    meaning: "The Provider",
    reflection: "Rely on Allah for sustenance and provision.",
  },
  {
    id: "al-fattah",
    arabic: "ٱلْفَتَّاحُ",
    transliteration: "Al-Fattah",
    meaning: "The Opener",
    reflection: "Ask Allah to open doors of guidance and ease.",
  },
  {
    id: "al-alim",
    arabic: "ٱلْعَلِيمُ",
    transliteration: "Al-'Alim",
    meaning: "The All-Knowing",
    reflection: "Trust that Allah knows your hidden struggles.",
  },
  {
    id: "al-qabid",
    arabic: "ٱلْقَابِضُ",
    transliteration: "Al-Qabid",
    meaning: "The Withholder",
    reflection: "Accept times of constriction as wisdom from Allah.",
  },
  {
    id: "al-basit",
    arabic: "ٱلْبَاسِطُ",
    transliteration: "Al-Basit",
    meaning: "The Expander",
    reflection: "Look for moments when Allah expands your heart.",
  },
  {
    id: "al-khafid",
    arabic: "ٱلْخَافِضُ",
    transliteration: "Al-Khafid",
    meaning: "The Reducer",
    reflection: "Remember that honor and humility are by Allah's will.",
  },
  {
    id: "ar-rafi",
    arabic: "ٱلرَّافِعُ",
    transliteration: "Ar-Rafi'",
    meaning: "The Exalter",
    reflection: "Seek elevation through sincerity and worship.",
  },
  {
    id: "al-muizz",
    arabic: "ٱلْمُعِزُّ",
    transliteration: "Al-Mu'izz",
    meaning: "The Bestower of Honor",
    reflection: "Ask Allah for dignity rooted in faith.",
  },
  {
    id: "al-mudhill",
    arabic: "ٱلْمُذِلُّ",
    transliteration: "Al-Mudhill",
    meaning: "The Humiliator",
    reflection: "Remain humble before Allah's decree.",
  },
  {
    id: "as-sami",
    arabic: "ٱلسَّمِيعُ",
    transliteration: "As-Sami'",
    meaning: "The All-Hearing",
    reflection: "Speak with sincerity knowing Allah hears every dua.",
  },
  {
    id: "al-basir",
    arabic: "ٱلْبَصِيرُ",
    transliteration: "Al-Basir",
    meaning: "The All-Seeing",
    reflection: "Let Allah's sight guide your actions.",
  },
  {
    id: "al-hakam",
    arabic: "ٱلْحَكَمُ",
    transliteration: "Al-Hakam",
    meaning: "The Judge",
    reflection: "Trust Allah's justice in every matter.",
  },
  {
    id: "al-adl",
    arabic: "ٱلْعَدْلُ",
    transliteration: "Al-'Adl",
    meaning: "The Just",
    reflection: "Strive for fairness because Allah loves justice.",
  },
  {
    id: "al-latif",
    arabic: "ٱللَّطِيفُ",
    transliteration: "Al-Latif",
    meaning: "The Subtle",
    reflection: "Notice Allah's gentle care in small details.",
  },
  {
    id: "al-khabir",
    arabic: "ٱلْخَبِيرُ",
    transliteration: "Al-Khabir",
    meaning: "The All-Aware",
    reflection: "Remember Allah knows what is hidden within you.",
  },
  {
    id: "al-halim",
    arabic: "ٱلْحَلِيمُ",
    transliteration: "Al-Halim",
    meaning: "The Forbearing",
    reflection: "Seek patience and gentleness modeled by Allah's forbearance.",
  },
  {
    id: "al-azim",
    arabic: "ٱلْعَظِيمُ",
    transliteration: "Al-'Azim",
    meaning: "The Magnificent",
    reflection: "Glorify Allah in every prayer and moment.",
  },
  {
    id: "al-ghafur",
    arabic: "ٱلْغَفُورُ",
    transliteration: "Al-Ghafur",
    meaning: "The Forgiving",
    reflection: "Turn to Allah with hope in His forgiveness.",
  },
  {
    id: "ash-shakur",
    arabic: "ٱلشَّكُورُ",
    transliteration: "Ash-Shakur",
    meaning: "The Appreciative",
    reflection: "Remember that Allah rewards even small deeds.",
  },
  {
    id: "al-ali",
    arabic: "ٱلْعَلِيُّ",
    transliteration: "Al-'Ali",
    meaning: "The Most High",
    reflection: "Lift your heart to Allah above all worries.",
  },
  {
    id: "al-kabir",
    arabic: "ٱلْكَبِيرُ",
    transliteration: "Al-Kabir",
    meaning: "The Greatest",
    reflection: "Acknowledge Allah's greatness in every situation.",
  },
  {
    id: "al-hafiz",
    arabic: "ٱلْحَفِيظُ",
    transliteration: "Al-Hafiz",
    meaning: "The Preserver",
    reflection: "Seek protection in Allah's preservation.",
  },
  {
    id: "al-muqit",
    arabic: "ٱلْمُقِيتُ",
    transliteration: "Al-Muqit",
    meaning: "The Sustainer",
    reflection: "Trust Allah to sustain you in every way.",
  },
  {
    id: "al-hasib",
    arabic: "ٱلْحَسِيبُ",
    transliteration: "Al-Hasib",
    meaning: "The Reckoner",
    reflection: "Rely on Allah's sufficiency and accountability.",
  },
  {
    id: "al-jalil",
    arabic: "ٱلْجَلِيلُ",
    transliteration: "Al-Jalil",
    meaning: "The Majestic",
    reflection: "Approach worship with reverence and awe.",
  },
  {
    id: "al-karim",
    arabic: "ٱلْكَرِيمُ",
    transliteration: "Al-Karim",
    meaning: "The Generous",
    reflection: "Remember Allah's generosity in your blessings.",
  },
  {
    id: "ar-raqib",
    arabic: "ٱلرَّقِيبُ",
    transliteration: "Ar-Raqib",
    meaning: "The Watchful",
    reflection: "Be mindful knowing Allah watches over all.",
  },
  {
    id: "al-mujib",
    arabic: "ٱلْمُجِيبُ",
    transliteration: "Al-Mujib",
    meaning: "The Responsive",
    reflection: "Call upon Allah with trust in His response.",
  },
  {
    id: "al-wasi",
    arabic: "ٱلْوَاسِعُ",
    transliteration: "Al-Wasi'",
    meaning: "The All-Encompassing",
    reflection: "Take comfort in Allah's expansive mercy.",
  },
  {
    id: "al-hakim",
    arabic: "ٱلْحَكِيمُ",
    transliteration: "Al-Hakim",
    meaning: "The All-Wise",
    reflection: "Trust the wisdom behind Allah's decree.",
  },
  {
    id: "al-wadud",
    arabic: "ٱلْوَدُودُ",
    transliteration: "Al-Wadud",
    meaning: "The Loving",
    reflection: "Remember Allah's love and share kindness with others.",
  },
  {
    id: "al-majid",
    arabic: "ٱلْمَجِيدُ",
    transliteration: "Al-Majid",
    meaning: "The Glorious",
    reflection: "Glorify Allah with gratitude for His honor.",
  },
  {
    id: "al-baith",
    arabic: "ٱلْبَاعِثُ",
    transliteration: "Al-Ba'ith",
    meaning: "The Resurrector",
    reflection: "Prepare for the Day of Resurrection with righteous deeds.",
  },
  {
    id: "ash-shahid",
    arabic: "ٱلشَّهِيدُ",
    transliteration: "Ash-Shahid",
    meaning: "The Witness",
    reflection: "Live with awareness that Allah witnesses every act.",
  },
  {
    id: "al-haqq",
    arabic: "ٱلْحَقُّ",
    transliteration: "Al-Haqq",
    meaning: "The Truth",
    reflection: "Anchor your life in Allah's truth.",
  },
  {
    id: "al-wakil",
    arabic: "ٱلْوَكِيلُ",
    transliteration: "Al-Wakil",
    meaning: "The Trustee",
    reflection: "Place your trust in Allah alone.",
  },
  {
    id: "al-qawiyy",
    arabic: "ٱلْقَوِيُّ",
    transliteration: "Al-Qawiyy",
    meaning: "The Strong",
    reflection: "Seek strength in Allah's power.",
  },
  {
    id: "al-matin",
    arabic: "ٱلْمَتِينُ",
    transliteration: "Al-Matin",
    meaning: "The Firm",
    reflection: "Ask Allah to keep your faith firm.",
  },
  {
    id: "al-wali",
    arabic: "ٱلْوَلِيُّ",
    transliteration: "Al-Wali",
    meaning: "The Protecting Friend",
    reflection: "Feel close to Allah as your guardian.",
  },
  {
    id: "al-hamid",
    arabic: "ٱلْحَمِيدُ",
    transliteration: "Al-Hamid",
    meaning: "The Praiseworthy",
    reflection: "Praise Allah for every blessing.",
  },
  {
    id: "al-muhsi",
    arabic: "ٱلْمُحْصِي",
    transliteration: "Al-Muhsi",
    meaning: "The Counter",
    reflection: "Remember Allah counts every act with justice.",
  },
  {
    id: "al-mubdi",
    arabic: "ٱلْمُبْدِئُ",
    transliteration: "Al-Mubdi'",
    meaning: "The Originator",
    reflection: "Reflect on Allah's ability to begin all things.",
  },
  {
    id: "al-muid",
    arabic: "ٱلْمُعِيدُ",
    transliteration: "Al-Mu'id",
    meaning: "The Restorer",
    reflection: "Trust Allah to restore what is lost.",
  },
  {
    id: "al-muhyi",
    arabic: "ٱلْمُحْيِي",
    transliteration: "Al-Muhyi",
    meaning: "The Giver of Life",
    reflection: "Recognize Allah's gift of life and renewal.",
  },
  {
    id: "al-mumit",
    arabic: "ٱلْمُمِيتُ",
    transliteration: "Al-Mumit",
    meaning: "The Taker of Life",
    reflection: "Remember the return to Allah with humility.",
  },
  {
    id: "al-hayy",
    arabic: "ٱلْحَيُّ",
    transliteration: "Al-Hayy",
    meaning: "The Ever-Living",
    reflection: "Seek closeness to the One who never fades.",
  },
  {
    id: "al-qayyum",
    arabic: "ٱلْقَيُّومُ",
    transliteration: "Al-Qayyum",
    meaning: "The Sustainer",
    reflection: "Rely on Allah who sustains all existence.",
  },
  {
    id: "al-wajid",
    arabic: "ٱلْوَاجِدُ",
    transliteration: "Al-Wajid",
    meaning: "The Finder",
    reflection: "Know that Allah is never in need.",
  },
  {
    id: "al-majid-2",
    arabic: "ٱلْمَاجِدُ",
    transliteration: "Al-Majid",
    meaning: "The Noble",
    reflection: "Honor Allah's nobility and generosity.",
  },
  {
    id: "al-wahid",
    arabic: "ٱلْوَاحِدُ",
    transliteration: "Al-Wahid",
    meaning: "The One",
    reflection: "Affirm Allah's oneness in every worship.",
  },
  {
    id: "al-ahad",
    arabic: "ٱلْأَحَدُ",
    transliteration: "Al-Ahad",
    meaning: "The Unique",
    reflection: "Let tawhid be the center of your heart.",
  },
  {
    id: "as-samad",
    arabic: "ٱلصَّمَدُ",
    transliteration: "As-Samad",
    meaning: "The Eternal",
    reflection: "Seek Allah in every need.",
  },
  {
    id: "al-qadir",
    arabic: "ٱلْقَادِرُ",
    transliteration: "Al-Qadir",
    meaning: "The All-Powerful",
    reflection: "Have hope in Allah's limitless power.",
  },
  {
    id: "al-muqtadir",
    arabic: "ٱلْمُقْتَدِرُ",
    transliteration: "Al-Muqtadir",
    meaning: "The Determiner",
    reflection: "Trust Allah's decree for every matter.",
  },
  {
    id: "al-muqaddim",
    arabic: "ٱلْمُقَدِّمُ",
    transliteration: "Al-Muqaddim",
    meaning: "The Expediter",
    reflection: "Rely on Allah's timing and wisdom.",
  },
  {
    id: "al-muakhkhir",
    arabic: "ٱلْمُؤَخِّرُ",
    transliteration: "Al-Mu'akhkhir",
    meaning: "The Delayer",
    reflection: "Accept delays as part of Allah's plan.",
  },
  {
    id: "al-awwal",
    arabic: "ٱلْأَوَّلُ",
    transliteration: "Al-Awwal",
    meaning: "The First",
    reflection: "Remember Allah existed before all things.",
  },
  {
    id: "al-akhir",
    arabic: "ٱلْآخِرُ",
    transliteration: "Al-Akhir",
    meaning: "The Last",
    reflection: "Return every affair to Allah in the end.",
  },
  {
    id: "az-zahir",
    arabic: "ٱلظَّاهِرُ",
    transliteration: "Az-Zahir",
    meaning: "The Manifest",
    reflection: "See Allah's signs in the world around you.",
  },
  {
    id: "al-batin",
    arabic: "ٱلْبَاطِنُ",
    transliteration: "Al-Batin",
    meaning: "The Hidden",
    reflection: "Remember Allah knows the hidden reality.",
  },
  {
    id: "al-wali-2",
    arabic: "ٱلْوَالِي",
    transliteration: "Al-Wali",
    meaning: "The Governor",
    reflection: "Submit to Allah's governance of all affairs.",
  },
  {
    id: "al-mutaali",
    arabic: "ٱلْمُتَعَالِي",
    transliteration: "Al-Muta'ali",
    meaning: "The Exalted",
    reflection: "Hold Allah above all created limitations.",
  },
  {
    id: "al-barr",
    arabic: "ٱلْبَرُّ",
    transliteration: "Al-Barr",
    meaning: "The Source of Goodness",
    reflection: "Seek goodness by remembering Allah's kindness.",
  },
  {
    id: "at-tawwab",
    arabic: "ٱلتَّوَّابُ",
    transliteration: "At-Tawwab",
    meaning: "The Accepter of Repentance",
    reflection: "Return to Allah often; He welcomes repentance.",
  },
  {
    id: "al-muntaqim",
    arabic: "ٱلْمُنْتَقِمُ",
    transliteration: "Al-Muntaqim",
    meaning: "The Avenger",
    reflection: "Leave justice to Allah and forgive others.",
  },
  {
    id: "al-afuw",
    arabic: "ٱلْعَفُوُّ",
    transliteration: "Al-'Afuw",
    meaning: "The Pardoner",
    reflection: "Seek Allah's pardon with humility.",
  },
  {
    id: "ar-rauf",
    arabic: "ٱلرَّءُوفُ",
    transliteration: "Ar-Ra'uf",
    meaning: "The Compassionate",
    reflection: "Receive Allah's gentleness with gratitude.",
  },
  {
    id: "malik-al-mulk",
    arabic: "مَالِكُ ٱلْمُلْكِ",
    transliteration: "Malik al-Mulk",
    meaning: "Master of the Kingdom",
    reflection: "Remember that all authority belongs to Allah.",
  },
  {
    id: "dhu-al-jalal",
    arabic: "ذُو ٱلْجَلَالِ وَٱلْإِكْرَامِ",
    transliteration: "Dhul-Jalali wal-Ikram",
    meaning: "Lord of Majesty and Honor",
    reflection: "Honor Allah with humility and gratitude.",
  },
  {
    id: "al-muqsit",
    arabic: "ٱلْمُقْسِطُ",
    transliteration: "Al-Muqsit",
    meaning: "The Equitable",
    reflection: "Strive to be fair in every relationship.",
  },
  {
    id: "al-jami",
    arabic: "ٱلْجَامِعُ",
    transliteration: "Al-Jami'",
    meaning: "The Gatherer",
    reflection: "Trust Allah to gather hearts upon truth.",
  },
  {
    id: "al-ghani",
    arabic: "ٱلْغَنِيُّ",
    transliteration: "Al-Ghani",
    meaning: "The Self-Sufficient",
    reflection: "Remember Allah needs nothing from creation.",
  },
  {
    id: "al-mughni",
    arabic: "ٱلْمُغْنِي",
    transliteration: "Al-Mughni",
    meaning: "The Enricher",
    reflection: "Ask Allah for contentment in your provision.",
  },
  {
    id: "al-mani",
    arabic: "ٱلْمَانِعُ",
    transliteration: "Al-Mani'",
    meaning: "The Withholder",
    reflection: "Trust Allah's protection in what is withheld.",
  },
  {
    id: "ad-darr",
    arabic: "ٱلضَّارُّ",
    transliteration: "Ad-Darr",
    meaning: "The Distresser",
    reflection: "Seek Allah's mercy in times of hardship.",
  },
  {
    id: "an-nafi",
    arabic: "ٱلنَّافِعُ",
    transliteration: "An-Nafi'",
    meaning: "The Benefiter",
    reflection: "Look for the good Allah brings in every situation.",
  },
  {
    id: "an-nur",
    arabic: "ٱلنُّورُ",
    transliteration: "An-Nur",
    meaning: "The Light",
    reflection: "Ask Allah to illuminate your path.",
  },
  {
    id: "al-hadi",
    arabic: "ٱلْهَادِي",
    transliteration: "Al-Hadi",
    meaning: "The Guide",
    reflection: "Seek guidance through prayer and Qur'an.",
  },
  {
    id: "al-badi",
    arabic: "ٱلْبَدِيعُ",
    transliteration: "Al-Badi'",
    meaning: "The Incomparable",
    reflection: "Marvel at Allah's unmatched perfection.",
  },
  {
    id: "al-baqi",
    arabic: "ٱلْبَاقِي",
    transliteration: "Al-Baqi",
    meaning: "The Everlasting",
    reflection: "Hold on to Allah; everything else fades.",
  },
  {
    id: "al-warith",
    arabic: "ٱلْوَارِثُ",
    transliteration: "Al-Warith",
    meaning: "The Inheritor",
    reflection: "Remember all returns to Allah in the end.",
  },
  {
    id: "ar-rashid",
    arabic: "ٱلرَّشِيدُ",
    transliteration: "Ar-Rashid",
    meaning: "The Guide to the Right Path",
    reflection: "Ask Allah to guide your decisions.",
  },
  {
    id: "as-sabur",
    arabic: "ٱلصَّبُورُ",
    transliteration: "As-Sabur",
    meaning: "The Patient",
    reflection: "Learn patience through Allah's example.",
  },
];
